name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update pip and setuptools
      run: python -m pip install --upgrade pip setuptools
    - name: Install Python Development Headers
      run: sudo apt update && sudo apt install -y python3-dev
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run tests
      run: pytest
