name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
