name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install wheel
      run: |
        python -m pip install wheel

    - name: Install setuptools
      run: |
        python -m pip install setuptools

    - name: Install six
      run: |
        python -m pip install six

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    # Add more steps as necessary
